export const APIUSER = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    city: "Gwenborough",
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    bio: "Multi-layered client-server neural-net",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    city: "Wisokyburgh",
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    bio: "Proactive didactic contingency",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    city: "McKenziehaven",
    phone: "1-463-123-4447",
    website: "ramiro.info",
    bio: "Face to face bifurcated interface",
  },
  {
    name: "Dhaval Makwana",
    username: "dhavalmakwana_26",
    email: "dhavalmakwana191@gmail.com",
    phone: "7600446773",
    website: "ola.org",
    city: "Amreli",
    bio: "Biooo",
    id: 4,
  },
  {
    name: "Milan",
    username: "mak",
    email: "tesr",
    phone: "7600446773",
    website: "sdfsd",
    city: "Amreli",
    bio: "Test",
    id: 6,
  },
  {
    name: "Dhaval Makwana",
    username: "dhavalmakwana_26",
    email: "dhavalmakwana191@gmail.com",
    phone: "7600446773",
    website: "test.com",
    city: "Surat",
    bio: "Bio",
    id: 7,
  },
  {
    name: "DM",
    username: "dm98@gmail.com",
    email: "dhavalmakwana@gmail.com",
    phone: "6356525696",
    website: "ramiro.info",
    city: "Una",
    bio: "BIo\n",
    id: 8,
  },
];
